server:
  port: 1299
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: aigou-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pandawjmb/aigou_config.git  #git文件地址
          username: pandaxswjmb@outlook.com
          password: XIONGwan!@34
